-- MySQL Script generated by MySQL Workbench
-- ven. 10 août 2018 14:51:59 +04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `phone_number` INT NOT NULL,
  `isCustomer` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trade-In_Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trade-In_Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serial_number` INT NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saler` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `experienced` TINYINT(1) NOT NULL,
  `phone_number` INT NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `manufacturer_price` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `id` INT NOT NULL,
  `vin` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  `manufacturer_name` VARCHAR(45) NOT NULL,
  `manufacturer_amount_price` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `idInvoice` INT NOT NULL,
  `trade_in_vehicle_allowed_amount` INT NOT NULL,
  `trade_in_dollar_allowed_amount` INT NOT NULL,
  `licence_fees` INT NOT NULL,
  `total_price` INT NOT NULL,
  `taxes` INT NOT NULL,
  `Saler_id` INT NOT NULL,
  `Person_id` INT NOT NULL,
  `Trade-In_Vehicle_id` INT NOT NULL,
  `Vehicle_id` INT NOT NULL,
  PRIMARY KEY (`idInvoice`, `Saler_id`, `Trade-In_Vehicle_id`, `Vehicle_id`),
  INDEX `fk_Invoice_Saler_idx` (`Saler_id` ASC),
  INDEX `fk_Invoice_Person1_idx` (`Person_id` ASC),
  INDEX `fk_Invoice_Trade-In_Vehicle1_idx` (`Trade-In_Vehicle_id` ASC),
  INDEX `fk_Invoice_Vehicle1_idx` (`Vehicle_id` ASC),
  CONSTRAINT `fk_Invoice_Saler`
    FOREIGN KEY (`Saler_id`)
    REFERENCES `mydb`.`Saler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Trade-In_Vehicle1`
    FOREIGN KEY (`Trade-In_Vehicle_id`)
    REFERENCES `mydb`.`Trade-In_Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Option_has_Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Option_has_Invoice` (
  `Option_id` INT NOT NULL,
  `Invoice_idInvoice` INT NOT NULL,
  `Option_has_Invoicecol` VARCHAR(45) NULL,
  PRIMARY KEY (`Option_id`, `Invoice_idInvoice`),
  INDEX `fk_Option_has_Invoice_Invoice1_idx` (`Invoice_idInvoice` ASC),
  INDEX `fk_Option_has_Invoice_Option1_idx` (`Option_id` ASC),
  CONSTRAINT `fk_Option_has_Invoice_Option1`
    FOREIGN KEY (`Option_id`)
    REFERENCES `mydb`.`Option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Option_has_Invoice_Invoice1`
    FOREIGN KEY (`Invoice_idInvoice`)
    REFERENCES `mydb`.`Invoice` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse_Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse_Cars` (
  `Vehicle_id` INT NOT NULL,
  `Trade-In_Vehicle_id` INT NOT NULL,
  PRIMARY KEY (`Vehicle_id`, `Trade-In_Vehicle_id`),
  INDEX `fk_Vehicle_has_Trade-In_Vehicle_Trade-In_Vehicle1_idx` (`Trade-In_Vehicle_id` ASC),
  INDEX `fk_Vehicle_has_Trade-In_Vehicle_Vehicle1_idx` (`Vehicle_id` ASC),
  CONSTRAINT `fk_Vehicle_has_Trade-In_Vehicle_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_has_Trade-In_Vehicle_Trade-In_Vehicle1`
    FOREIGN KEY (`Trade-In_Vehicle_id`)
    REFERENCES `mydb`.`Trade-In_Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
